config/routes.rb
Rails.application.routes.draw do
  get 'navigator/index'
  post 'navigator/index'
  get 'guiders_login' => 'guiders_sessions#new'
  post 'guiders_login' => 'guiders_sessions#create'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'workspace' => 'sessions#show'#this should be changed into the address of worksspace

  post 'logout' => 'sessions#destroy'
  post 'guiders_logout' => 'guiders_sessions#destroy'

  resources :travelers 
  resources :guiders
  resources :travelers do 
    resources :ordered_trips
  end
  resources :trip_goods
  get 'trip_goods/detail/:id' => 'trip_goods#detail'
  resources :ordered_trips
  post 'search_goods' => 'trip_goods#search'
  get 'search_goods' => 'travelers#show'
  

   root 'navigator#index'

end

app/models/catagory.rb
class Catagory < ActiveRecord::Base
  belongs_to :trip_good
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :states
  has_many :trip_goods
end

app/models/country.rb
class Country < ActiveRecord::Base
has_many :states
end

app/models/guider.rb
class Guider < ActiveRecord::Base
  has_many :ordered_trips
  has_many :paying_methods
  has_secure_password
  validates :email,:first_name,:last_name,:contact_number,
  presence: true,
  :on => [ :create ]
  validates :password,
  length: { in: 6..20,
             to_short: "your password should be at least %{count} characters",
             to_long: "your password should be at most %{count} characters" },
  :on => [ :create ]
  #validates :email
  validates :email, email: true
  ##validates_email_realness_of :email
  EmailVerifier.config do |config|
   config.verifier_email = "realname@realdomain.com"
  end
  ###################################
  #validates :name validator
  INVALID_NAME_REGEX = /[^a-zA-Z	 ]/
  validates :first_name,:last_name,
  length: { maximum: 20 },
  format: { without: INVALID_NAME_REGEX }
  #validates :unique email                                  
  validates  :email,
  uniqueness: { case_sensitive: false, on: [:create] }
  #####################################
  #validates :number validator 
  INVALID_NUMBER_REGEX = /[^0-9 	]/
  validates :contact_number,
  length: { maximum: 20 },
  format: { without: INVALID_NUMBER_REGEX }
end

app/models/language.rb
class Language < ActiveRecord::Base
  belongs_to :guider
end

app/models/ordered_trip.rb
class OrderedTrip < ActiveRecord::Base
  belongs_to :trip_good
  belongs_to :plan
  belongs_to :traveler
end

app/models/paying_method.rb
class PayingMethod < ActiveRecord::Base
  belongs_to :traveler
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	has_many :ordered_trip
end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :countries
  has_many :cities
end

app/models/traveler.rb
class Traveler < ActiveRecord::Base
  has_many :ordered_trips
  has_many :paying_methods
  has_secure_password
  validates :email,:first_name,:last_name,:contact_number,
  presence: true,
  :on => [ :create ]
  validates :password,
  length: { in: 6..20,
             to_short: "your password should be at least %{count} characters",
             to_long: "your password should be at most %{count} characters" },
  :on => [ :create ]
  #validates :email
  validates :email, email: true
  ##validates_email_realness_of :email
  EmailVerifier.config do |config|
   config.verifier_email = "realname@realdomain.com"
  end
  ###################################
  #validates :name validator
  INVALID_NAME_REGEX = /[^a-zA-Z	 ]/
  validates :first_name,:last_name,
  length: { maximum: 20 },
  format: { without: INVALID_NAME_REGEX }
  #validates :unique email                                  
  validates  :email,
  uniqueness: { case_sensitive: false, on: [:create] }
  #####################################
  #validates :number validator 
  INVALID_NUMBER_REGEX = /[^0-9 	]/
  validates :contact_number,
  length: { maximum: 20 },
  format: { without: INVALID_NUMBER_REGEX }
  
  
end

app/models/trip_good.rb
class TripGood < ActiveRecord::Base
  belongs_to :city
  belongs_to :guider
  has_many :catagories
  has_many :ordered_trips
  validates :beginning_date, presence: true
  validates :end_date, presence: true
end

app/controllers/guiders_controller.rb
class GuidersController < ApplicationController
  def index
   redirect_to action: 'new' 
  end
  
  def new
    @guider = Guider.new
  end
  
  def edit
       @guider = Guider.find_by(id: session[:id])  
  end
  
  def create
    @guider = Guider.new(guider_params)
    if @guider.save
     redirect_to guiders_login_path 
    else  
     flash.now[:danger] = 'Registration failed, some information is missing!'  
     render 'new'
    end  
  end
   def update
    @guider = Guider.find_by(id: session[:id])
    if @guider.update(guider_params)
      flash[:danger]="Update succeeded!"      
      redirect_to @guider
    else 
      flash[:danger]="Update failed!" 
      redirect_to @guider
    end 
  end
  
  def show
    @guider = Guider.find_by(id: session[:id])
     if !flash[:danger]
      flash.now[:notice] = 'Welcome back! Dear '+ @guider.first_name
     end
  end
  
   def guider_tripgoods
     @guider = Guider.find_by(id: session[:id])
     @trip_goods= @guider.trip_goods;
   end
   
  def guider_params
   params.require(:guider).permit(:attachment,:first_name,:middle_name,:last_name,:password,:password_confirmation,:email,:username,:gender,:age,:photo,:contact_number,:alter_number,:street_address,:country,:city,:state,:zip_code, :passport_number, :driver_license, :SSN, :rating, :introduction, :comment)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def new
   flash.now[:notice] = 'Congratulations!Now go ahead and login!'
   @traveler =Traveler.new
 end
  def create
   @traveler = Traveler.find_by(email: params[:session][:email].downcase)
  #@traveler.authenticate('123456')
   if @traveler && @traveler.authenticate(params[:session][:password])
      traveler_log_in @traveler
      redirect_to @traveler
    else
      flash.now[:danger] = 'Wrong email/password combination!'
      render 'new'
    end
  end

  def destroy
    if session[:id]
      session[:id]=nil
    end
    redirect_to '/navigator/index' 
  end
  
end

app/controllers/travelers_controller.rb
class TravelersController < ApplicationController
  def index
   redirect_to action: 'new' 
  end
  
  def new
    @traveler = Traveler.new
  end
  
  def edit
      @traveler = Traveler.find_by(id: session[:id])  
  end
  def update
    @traveler = Traveler.find_by(id: session[:id])
    if @traveler.update(traveler_params)
      flash[:danger]="Update succeeded!"      
      redirect_to @traveler
    else 
      flash[:danger]="Update failed!" 
      redirect_to @traveler     
    end 
  end
  def create
    @traveler = Traveler.new(traveler_params)
    if @traveler.save
     redirect_to login_path
    else  
      flash.now[:danger] = 'Registration failed, some information is missing!'  
      render 'new'
    end  
  end
  
  def show
    @traveler = Traveler.find_by(id: session[:id])
    if !flash[:danger]
     flash.now[:notice] = 'Welcome back! Dear '+ @traveler.first_name
    end
  end
  def traveler_params
   params.require(:traveler).permit(:attachment,:first_name,:middle_name,:last_name,:password,:password_confirmation,:email,:username,:gender,:age,:photo,:contact_number,:alter_number,:street_address,:city,:state,:zip_code,:country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guiders_helper.rb
module GuidersHelper
end

app/helpers/navigator_helper.rb
module NavigatorHelper
end

app/helpers/ordered_trips_helper.rb
module OrderedTripsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def traveler_log_in(traveler)
    session[:id] = traveler.id
  end
end

app/helpers/travelers_helper.rb
module TravelersHelper
end

app/helpers/trip_goods_helper.rb
module TripGoodsHelper
end

app/views/travelers/_basic_info.html.haml
%fieldset
 %h3 Profile
 %div{:id=>'@traveler',:class=>'basic_info'}
  %strong
   Photo
  %br 
  %img{:src=>"http://i2.hdslb.com/video/31/31fd26b6842ef1fe811c020324d80a1e.jpg",:alt=>"HTML5 Icon",:style=>"width:300px;height:222px;"}
  %br
  %strong 
   Name:
  = @traveler.first_name
  = @traveler.middle_name
  = @traveler.last_name
  %br
  %strong
   Age: 
  = @traveler.age
  %br
  %strong
   Gender:
  = @traveler.gender 
  %br
  %strong 
   My Current Street
  %br 
  %strong
   street:
  = @traveler.street_address
  %strong
   city:
  = @traveler.city
  %strong
   state:
  = @traveler.state
  %strong
   country:
  = @traveler.country
  %strong
   zip_code:
  = @traveler.zip_code

app/views/travelers/_navigation_bar.html.haml
.navbar.navbar-fixed-top.navbar-inverse
 .container
  %h1 Travel Uber
  %nav
   %ul{:class=>"nav navbar-nav navbar-right"} 
    %li
     =link_to "Home", "/travelers/show"
    %li
     =link_to "Ordered goods",ordered_trips_path
    %li
     =link_to "Profile", "#"
    %li
     =link_to "Logout","/logout",:method=>'post'

app/views/travelers/_update_profile.html.haml
%fieldset  
 %h3 Update my profile
 =form_for @traveler, html: { multipart: true } do |f|
  =f.text_field :first_name, {:placeholder => 'Firstname'}
  =f.text_field :middle_name, {:placeholder => 'Middlename'}
  =f.text_field :last_name,  {:placeholder => 'Lastname'}
  %div{:style => "margin-bottom:10px"}
  =f.text_field :contact_number, {:placeholder => 'Primary Contact Number'}
  =f.text_field :alter_number, {:placeholder => 'Alternate Contact Number'}
  %div{:style => "margin-bottom:10px"}
  =f.text_field :age, {:placeholder => 'age'}
  =f.text_field :gender, {:placeholder => 'gender'}
  %div{:style => "margin-bottom:10px"}
  %div{:style => "margin-bottom:10px"}
  =f.text_field :street_address, {:placeholder => 'street_address'}
  =f.text_field :city, {:placeholder => 'city'}
  %div{:style => "margin-bottom:10px"}
  =f.text_field :state, {:placeholder => 'state'}
  =f.text_field :country, {:placeholder => 'country'}
  %div{:style => "margin-bottom:10px"}
  =f.text_field :zip_code, {:placeholder => 'zip_code'}
  =f.label :attachment
  =f.file_field :attachment
  %p
  =f.submit 'Update my profile'

app/views/travelers/new.html.haml
%div
 =render 'guiders/signup_bar'
 .container1.container
  .myedit.well.e1
   %h2 Current Users
   =render 'sessions/signin'
   %fieldset
    -if @traveler.errors.any?
     %div{:id=>"error_explanations"}
      =pluralize(@traveler.errors.count, "error") #count the amount of errors(error)
      has been found!
      %ul
       -@traveler.errors.full_messages.each do |msg|
        %li
         =msg
    %h2 New Users    
    =form_for @traveler do |f|
     =f.text_field :first_name, {:placeholder => 'Firstname'}
     =f.text_field :middle_name, {:placeholder => 'Middlename'}
     =f.text_field :last_name,  {:placeholder => 'Lastname'}
     %div{:style => "margin-bottom:10px"}
     =f.text_field :email, {:placeholder => 'E-mail'}
     =f.text_field :password, {:type=>'password',:placeholder => 'password'}
     %div{:style => "margin-bottom:10px"}
     =f.text_field :contact_number, {:placeholder => 'Primary Contact Number'}
     =f.text_field :alter_number, {:placeholder => 'Alternate Contact Number'}
     %div{:style => "margin-bottom:10px"}
     %p
     =f.submit 'Join us now!'

app/views/travelers/show.html.haml
%h1 Travel Uber
=render 'navigation_bar'
.container1.container
%br
%br
%flash
 =flash[:notice]
 =flash[:danger]
 =render 'basic_info'
 =render 'update_profile'
 %div{:id=>'search',:class=>'button'}
  =button_to 'Find my dream trips!', search_goods_path 